### ISSUE TITLE
fails horribly with softhsm2

### ISSUE THREAD

**Issue by oerdnj** [miekg/pkcs11#27] opened 2016-04-07 00:46 UTC
Hi Miek, I am in process of removing softhsm(1) from Debian, and your package is one of the two that depends on the old one. Could you please switch to libsofthsm2.so and fix this?

```
    go test -v github.com/miekg/pkcs11
=== RUN   TestSetenv
--- PASS: TestSetenv (0.00s)
=== RUN   TestInitialize
--- FAIL: TestInitialize (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:77: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   TestGetInfo
--- FAIL: TestGetInfo (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   TestFindObject
--- FAIL: TestFindObject (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   TestGetAttributeValue
--- FAIL: TestGetAttributeValue (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   TestDigest
--- FAIL: TestDigest (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   TestDigestUpdate
--- FAIL: TestDigestUpdate (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   TestGenerateKeyPair
--- FAIL: TestGenerateKeyPair (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   TestSign
--- FAIL: TestSign (0.00s)
    pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
    pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
=== RUN   ExampleSign
--- FAIL: ExampleSign (0.00s)
panic: runtime error: index out of range [recovered]
    panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5a2e80, 0xc820014060)
    /usr/lib/go/src/runtime/panic.go:464 +0x3e6
testing.runExample.func2(0xece97a492, 0xc81da65164, 0x8cd7a0, 0xc820076080, 0xc820076008, 0xc8200884e0, 0x5dbf60, 0xb, 0x629800, 0x5dc4b0, ...)
    /usr/lib/go/src/testing/example.go:93 +0x3fa
panic(0x5a2e80, 0xc820014060)
    /usr/lib/go/src/runtime/panic.go:426 +0x4e9
github.com/miekg/pkcs11.ExampleSign()
    /tmp/build-area/golang-github-miekg-pkcs11-0.0~git20160222.0.df8ae6ca/obj-x86_64-linux-gnu/src/github.com/miekg/pkcs11/pkcs11_test.go:292 +0x1149
testing.runExample(0x5dbf60, 0xb, 0x629800, 0x5dc4b0, 0xa, 0x0)
    /usr/lib/go/src/testing/example.go:98 +0x3d7
testing.RunExamples(0x629868, 0x8b7da0, 0x1, 0x1, 0x1)
    /usr/lib/go/src/testing/example.go:36 +0x314
testing.(*M).Run(0xc82004bef8, 0xc82004be88)
    /usr/lib/go/src/testing/testing.go:516 +0xbd
main.main()
    github.com/miekg/pkcs11/_test/_testmain.go:72 +0x117
exit status 2
FAIL    github.com/miekg/pkcs11 0.009s
```

**Comment by miekg** [comment] 2016-04-07 05:57
[ Quoting <notifications@github.com> in "[miekg/pkcs11] fails horribly with ..." ]
>Hi Miek, I am in process of removing softhsm(1) from Debian, and your package is one of the two that depends on the old one. Could you please switch to libsofthsm2.so and fix this?

Interesting failures.... I'll try to take a look.

>```
>	go test -v github.com/miekg/pkcs11
>=== RUN   TestSetenv
>--- PASS: TestSetenv (0.00s)
>=== RUN   TestInitialize
>--- FAIL: TestInitialize (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:77: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   TestGetInfo
>--- FAIL: TestGetInfo (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   TestFindObject
>--- FAIL: TestFindObject (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   TestGetAttributeValue
>--- FAIL: TestGetAttributeValue (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   TestDigest
>--- FAIL: TestDigest (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   TestDigestUpdate
>--- FAIL: TestDigestUpdate (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   TestGenerateKeyPair
>--- FAIL: TestGenerateKeyPair (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   TestSign
>--- FAIL: TestSign (0.00s)
>	pkcs11_test.go:32: loading /usr/lib/softhsm/libsofthsm2.so
>	pkcs11_test.go:58: init error pkcs11: 0x5: CKR_GENERAL_ERROR
>=== RUN   ExampleSign
>--- FAIL: ExampleSign (0.00s)
>panic: runtime error: index out of range [recovered]
>	panic: runtime error: index out of range
>
>goroutine 1 [running]:
>panic(0x5a2e80, 0xc820014060)
>	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
>testing.runExample.func2(0xece97a492, 0xc81da65164, 0x8cd7a0, 0xc820076080, 0xc820076008, 0xc8200884e0, 0x5dbf60, 0xb, 0x629800, 0x5dc4b0, ...)
>	/usr/lib/go/src/testing/example.go:93 +0x3fa
>panic(0x5a2e80, 0xc820014060)
>	/usr/lib/go/src/runtime/panic.go:426 +0x4e9
>github.com/miekg/pkcs11.ExampleSign()
>	/tmp/build-area/golang-github-miekg-pkcs11-0.0~git20160222.0.df8ae6ca/obj-x86_64-linux-gnu/src/github.com/miekg/pkcs11/pkcs11_test.go:292 +0x1149
>testing.runExample(0x5dbf60, 0xb, 0x629800, 0x5dc4b0, 0xa, 0x0)
>	/usr/lib/go/src/testing/example.go:98 +0x3d7
>testing.RunExamples(0x629868, 0x8b7da0, 0x1, 0x1, 0x1)
>	/usr/lib/go/src/testing/example.go:36 +0x314
>testing.(*M).Run(0xc82004bef8, 0xc82004be88)
>	/usr/lib/go/src/testing/testing.go:516 +0xbd
>main.main()
>	github.com/miekg/pkcs11/_test/_testmain.go:72 +0x117
>exit status 2
>FAIL	github.com/miekg/pkcs11	0.009s
>```
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/miekg/pkcs11/issues/27
/Miek

--
Miek Gieben

**Comment by onlyjob** [comment] 2016-05-01 11:12
It would be great to dedicate this problem a little attention as _softhsm1_ is going away...

**Comment by miekg** [comment] 2016-05-01 12:32
I prolly *won't* be able to create enough time to tackle this in next few weeks.

**Comment by miekg** [comment] 2016-05-07 15:39
So... I looked a bit. The initialization fails... I have no idea why. This *almost* looks like a problem with softhsmv2, but I am nowhere near actually finding out where the issue is.

**Comment by epim** [comment] 2016-05-09 23:06
declare -x SOFTHSM_LIB="/usr/lib64/pkcs11/libsofthsm2.so"
declare -x SOFTHSM_PIN="123456"
=== RUN   TestSetenv
--- PASS: TestSetenv (0.00s)
=== RUN   TestInitialize
--- PASS: TestInitialize (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestGetInfo
--- PASS: TestGetInfo (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
	pkcs11_test.go:101: {CryptokiVersion:{Major:2 Minor:30} ManufacturerID:SoftHSM Flags:0 LibraryDescription:Implementation of PKCS11 LibraryVersion:{Major:2 Minor:0}}
=== RUN   TestFindObject
--- FAIL: TestFindObject (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
	pkcs11_test.go:121: should have found two objects
=== RUN   TestGetAttributeValue
--- FAIL: TestGetAttributeValue (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
	pkcs11_test.go:139: err pkcs11: 0x82: CKR_OBJECT_HANDLE_INVALID
=== RUN   TestDigest
--- PASS: TestDigest (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestDigestUpdate
--- PASS: TestDigestUpdate (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestGenerateKeyPair
--- FAIL: TestGenerateKeyPair (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
	pkcs11_test.go:221: failed to generate keypair: pkcs11: 0xD1: CKR_TEMPLATE_INCONSISTENT
=== RUN   TestSign
--- FAIL: TestSign (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
	pkcs11_test.go:221: failed to generate keypair: pkcs11: 0xD1: CKR_TEMPLATE_INCONSISTENT
=== RUN   ExampleSign
2016/05/09 23:05:10 pkcs11: 0xD1: CKR_TEMPLATE_INCONSISTENT
exit status 1

It gets further if you run it as root. The problem i'm seeing now may be user error. I'll keep poking at it.

**Comment by miekg** [comment] 2016-05-10 08:30
[ Quoting <notifications@github.com> in "Re: [miekg/pkcs11] fails horribly w..." ]
>declare -x SOFTHSM_LIB="/usr/lib64/pkcs11/libsofthsm2.so"
>declare -x SOFTHSM_PIN="123456"
>=== RUN   TestSetenv
>--- PASS: TestSetenv (0.00s)
>=== RUN   TestInitialize
>--- PASS: TestInitialize (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>=== RUN   TestGetInfo
>--- PASS: TestGetInfo (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>	pkcs11_test.go:101: {CryptokiVersion:{Major:2 Minor:30} ManufacturerID:SoftHSM Flags:0 LibraryDescription:Implementation of PKCS11 LibraryVersion:{Major:2 Minor:0}}
>=== RUN   TestFindObject
>--- FAIL: TestFindObject (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>	pkcs11_test.go:121: should have found two objects
>=== RUN   TestGetAttributeValue
>--- FAIL: TestGetAttributeValue (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>	pkcs11_test.go:139: err pkcs11: 0x82: CKR_OBJECT_HANDLE_INVALID
>=== RUN   TestDigest
>--- PASS: TestDigest (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>=== RUN   TestDigestUpdate
>--- PASS: TestDigestUpdate (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>=== RUN   TestGenerateKeyPair
>--- FAIL: TestGenerateKeyPair (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>	pkcs11_test.go:221: failed to generate keypair: pkcs11: 0xD1: CKR_TEMPLATE_INCONSISTENT
>=== RUN   TestSign
>--- FAIL: TestSign (0.00s)
>	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
>	pkcs11_test.go:221: failed to generate keypair: pkcs11: 0xD1: CKR_TEMPLATE_INCONSISTENT
>=== RUN   ExampleSign
>2016/05/09 23:05:10 pkcs11: 0xD1: CKR_TEMPLATE_INCONSISTENT
>exit status 1
>
>It gets further if you run it as root. The problem i'm seeing now may be user error. I'll keep poking at it.

This is without any code changes?

/Miek

--
Miek Gieben

**Comment by epim** [comment] 2016-05-10 16:41
No code changes

**Comment by epim** [comment] 2016-05-11 23:47
PR31 fixed the template errors, and i've opened PR32 to fix the other errors.. And do some other stuff.

`
[penick@whirlgirl pkcs11]$ declare -x SOFTHSM_PIN="1234"
[penick@whirlgirl pkcs11]$  declare -x SOFTHSM_LIB=/usr/lib64/pkcs11/libsofthsm2.so
[penick@whirlgirl pkcs11]$ sudo -E go test -v ./...
=== RUN   TestSetenv
--- PASS: TestSetenv (0.00s)
=== RUN   TestInitialize
--- PASS: TestInitialize (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestGetInfo
--- PASS: TestGetInfo (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
	pkcs11_test.go:101: {CryptokiVersion:{Major:2 Minor:30} ManufacturerID:SoftHSM Flags:0 LibraryDescription:Implementation of PKCS11 LibraryVersion:{Major:2 Minor:0}}
=== RUN   TestFindObject
--- PASS: TestFindObject (0.18s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestGetAttributeValue
--- PASS: TestGetAttributeValue (0.22s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
	pkcs11_test.go:148: attr 0, type 290, valuelen 3
	pkcs11_test.go:148: attr 1, type 289, valuelen 8
	pkcs11_test.go:148: attr 2, type 288, valuelen 256
	pkcs11_test.go:152: modulus 22298023224031648719717149305237016158935633201602592336087002856959570278362664390446865768619390528431531067357573211640531654896045041360594742165847635555275225864681779776612611080285698141376393532788650692694259208765466093412015839667240648689492053125099094171082940025319163355064074268567710747259094443770745151593496505422218980560055168291697177404835600700636219919148547754767876983950485863203196110853083861313304306137005378647095488631550479839464676013953164273280392211107052372477152167741615333564413164586622422232892705035945284849132687688386540954598329637739839571295038736558112140759743
	pkcs11_test.go:148: attr 3, type 3, valuelen 17
=== RUN   TestDigest
--- PASS: TestDigest (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestDigestUpdate
--- PASS: TestDigestUpdate (0.00s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestGenerateKeyPair
--- PASS: TestGenerateKeyPair (0.16s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestSign
--- PASS: TestSign (0.06s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   TestDestroyObject
--- PASS: TestDestroyObject (0.08s)
	pkcs11_test.go:32: loading /usr/lib64/pkcs11/libsofthsm2.so
=== RUN   ExampleSign
--- PASS: ExampleSign (0.04s)
PASS
ok  	github.com/pkcs11	0.755s
[penick@whirlgirl pkcs11]$`

**Comment by epim** [comment] 2016-05-16 17:22
@oerdnj PR 32 was merged. Your tests should pass now as long as you run pkcs11_test.go with credentials sufficient to read /var/lib/softhsm/tokens/ , which is read only to root by default.

**Comment by miekg** [comment] 2016-05-31 22:06
I think this can be closed now, no? Thansk @epim for you hard work on this!

**Comment by anitgandhi** [comment] 2016-08-19 16:43
On the latest versions of SoftHSMv2 (develop branch), GetTokenInfo won't work because the way SoftHSMv2 labels the slots has changed, as explained [here](https://github.com/opendnssec/SoftHSMv2/issues/225). Basically the newly initialized token serial number becomes the slot id. 

But, if you try and call GetSlotInfo on each slot to find the right one (in this case slot "0"), then GetTokenInfo(slot_number) where slot_number is going to be 0, it will fail since the slot number is actually some large number that represents its token's serial number. 

That change hasn't worked its way into the master branch of SoftHSMv2 yet, so this pkcs11 package works fine with that. But, on the develop branch, it won't work. I feel this may be a breaking change that needs to be accounted for.

**Closed** 2018-02-08 12:39 UTC
