### ISSUE TITLE
go build github.com/hyperledger/fabric/vendor/github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool

### ISSUE THREAD

**Issue by friends110110** [miekg/pkcs11#67] opened 2018-03-05 02:22 UTC

**Comment by mtharp** [comment] 2018-03-05 13:54
Duplicate of #63 -- I recommend upgrading to go1.10

**Closed by mtharp** 2018-03-05 13:54 UTC
Labels: duplicate

**Comment by monofire** [comment] 2018-03-06 23:20
Experienced same issue with GO v1.10

go build github.com/hyperledger/fabric/vendor/github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool #67

**Comment by mtharp** [comment] 2018-03-07 02:24
The project you are building (fabric) has vendored an old copy of the pkcs11 library that no longer builds on current versions of Go. Here is the fabric issue for this: https://jira.hyperledger.org/browse/FAB-8358 . It looks like the 1.1 release will incorporate a newer pkcs11 library. You *may* be able to fix the build by deleting the vendor/github.com/miekg/pkcs11 directory so that the latest version is pulled, but I can't really provide project-specific assistance beyond that.

You can also bypass the new security check by setting the environment variable CGO_LDFLAGS_ALLOW="-I.*" -- see here https://golang.org/cmd/cgo/

**Comment by monofire** [comment] 2018-03-07 20:10
@mtharp, thank you for the prompt reply. 
Solved that by rolling back to Go 1.9.3
